---
#Path Information
dest_myhosts_file: /etc

#vault Information
vault_version: "1.3.2"
vault_group: "vault"
vault_user: "vault"
vault_mode: "0775"
root_mode: "root"
root_group: "root"

vault_binary_directory_path: "/usr/local/bin"
vault_directory_path: "/etc/vault.d"
vault_log_directory: "/var/log/vault-log"
vault_log_file_path: "/var/log/vault-log/vault-audit.log"
vault_configuration_file: "/etc/vault.d/config.json"
vault_systemd_file: "/etc/systemd/system/vault.service"

vault_server_1:
vault_server_2:
vault_server_3:

node_name_1: vault-client-01
node_name_2: secops-client-02
node_name_3: secops-nodes-03

cluster_address: 10.99.3.134:8201
api_addr: http://10.99.3.134:8200
cluster_addr: http://10.99.3.134:8201
